"""agregar nombre a usuarios (login con Google)

Revision ID: db8e00ae811e
Revises: 7ce6c28d40dc
Create Date: 2026-09-16 15:40:08.805200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8e00ae811e'
down_revision: Union[str, None] = '7ce6c28d40dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nombre', sa.String(length=150), nullable=True), schema='offix')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nombre', schema='offix')
    # ### end Alembic commands ###
