"""esquema inicial sprint 1

Crea en el schema `offix` todas las tablas del backend al cierre de Sprint 1
(HU-01, HU-02, HU-03). No toca el schema `public`, donde está materializado el
DER original de la PM.

Revision ID: 7ce6c28d40dc
Revises: 
Create Date: 2026-09-16 13:49:34.777009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce6c28d40dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Redundante cuando se migra conectado (env.py ya lo crea), pero deja el SQL
    # exportado con `alembic upgrade head --sql` completo por sí mismo.
    op.execute('CREATE SCHEMA IF NOT EXISTS offix')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre'),
    schema='offix'
    )
    op.create_index(op.f('ix_offix_categorias_id_categoria'), 'categorias', ['id_categoria'], unique=False, schema='offix')
    op.create_table('padron_matriculas',
    sa.Column('id_padron', sa.Integer(), nullable=False),
    sa.Column('tipo_profesional', sa.String(length=50), nullable=False),
    sa.Column('numero_matricula', sa.String(length=20), nullable=False),
    sa.Column('nombre_matriculado', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_padron'),
    sa.UniqueConstraint('tipo_profesional', 'numero_matricula', name='uq_padron_tipo_numero'),
    schema='offix'
    )
    op.create_index(op.f('ix_offix_padron_matriculas_id_padron'), 'padron_matriculas', ['id_padron'], unique=False, schema='offix')
    op.create_index(op.f('ix_offix_padron_matriculas_numero_matricula'), 'padron_matriculas', ['numero_matricula'], unique=False, schema='offix')
    op.create_index(op.f('ix_offix_padron_matriculas_tipo_profesional'), 'padron_matriculas', ['tipo_profesional'], unique=False, schema='offix')
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('Oferente', 'Administrador', name='rol_usuario', native_enum=False, length=50), nullable=False),
    sa.Column('estado_cuenta', sa.String(length=50), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    schema='offix'
    )
    op.create_index(op.f('ix_offix_usuarios_email'), 'usuarios', ['email'], unique=True, schema='offix')
    op.create_index(op.f('ix_offix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False, schema='offix')
    op.create_table('oferentes',
    sa.Column('id_oferente', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni_cuit', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('numero_matricula', sa.String(length=100), nullable=True),
    sa.Column('estado_verificacion', sa.String(length=50), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('radio_cobertura_km', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hora_inicio_atencion', sa.Time(), nullable=True),
    sa.Column('hora_fin_atencion', sa.Time(), nullable=True),
    sa.Column('disponible_emergencia', sa.Boolean(), nullable=False),
    sa.Column('promedio_calificacion', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad_rechazos_acumulados', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['offix.categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_oferente'], ['offix.usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_oferente'),
    sa.UniqueConstraint('dni_cuit'),
    schema='offix'
    )
    op.create_table('alertas_administrador',
    sa.Column('id_alerta', sa.Integer(), nullable=False),
    sa.Column('oferente_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado_revision', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['oferente_id'], ['offix.oferentes.id_oferente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_alerta'),
    schema='offix'
    )
    op.create_index(op.f('ix_offix_alertas_administrador_id_alerta'), 'alertas_administrador', ['id_alerta'], unique=False, schema='offix')
    op.create_index(op.f('ix_offix_alertas_administrador_oferente_id'), 'alertas_administrador', ['oferente_id'], unique=False, schema='offix')
    op.create_table('archivos_adjuntos',
    sa.Column('id_archivo', sa.Integer(), nullable=False),
    sa.Column('oferente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('url_archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['oferente_id'], ['offix.oferentes.id_oferente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_archivo'),
    schema='offix'
    )
    op.create_index(op.f('ix_offix_archivos_adjuntos_id_archivo'), 'archivos_adjuntos', ['id_archivo'], unique=False, schema='offix')
    op.create_index(op.f('ix_offix_archivos_adjuntos_oferente_id'), 'archivos_adjuntos', ['oferente_id'], unique=False, schema='offix')
    op.create_table('matriculas',
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('oferente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_profesional', sa.String(length=50), nullable=False),
    sa.Column('numero_matricula', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_fidelizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oferente_id'], ['offix.oferentes.id_oferente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_matricula'),
    sa.UniqueConstraint('oferente_id', 'tipo_profesional', name='uq_matricula_oferente_tipo'),
    schema='offix'
    )
    op.create_index(op.f('ix_offix_matriculas_id_matricula'), 'matriculas', ['id_matricula'], unique=False, schema='offix')
    op.create_index(op.f('ix_offix_matriculas_oferente_id'), 'matriculas', ['oferente_id'], unique=False, schema='offix')
    op.create_table('solicitudes_resena',
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('oferente_id', sa.Integer(), nullable=False),
    sa.Column('codigo_unico', sa.String(length=100), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=False),
    sa.Column('telefono_cliente', sa.String(length=20), nullable=True),
    sa.Column('email_cliente', sa.String(length=255), nullable=True),
    sa.Column('origen', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('intentos_rechazo', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['oferente_id'], ['offix.oferentes.id_oferente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_solicitud'),
    schema='offix'
    )
    op.create_index(op.f('ix_offix_solicitudes_resena_codigo_unico'), 'solicitudes_resena', ['codigo_unico'], unique=True, schema='offix')
    op.create_index(op.f('ix_offix_solicitudes_resena_id_solicitud'), 'solicitudes_resena', ['id_solicitud'], unique=False, schema='offix')
    op.create_index(op.f('ix_offix_solicitudes_resena_oferente_id'), 'solicitudes_resena', ['oferente_id'], unique=False, schema='offix')
    op.create_table('validaciones_matricula',
    sa.Column('id_validacion', sa.Integer(), nullable=False),
    sa.Column('oferente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_profesional', sa.String(length=50), nullable=False),
    sa.Column('numero_matricula', sa.String(length=20), nullable=False),
    sa.Column('resultado', sa.String(length=50), nullable=False),
    sa.Column('categoria_padron', sa.String(length=50), nullable=True),
    sa.Column('fecha_vencimiento_padron', sa.Date(), nullable=True),
    sa.Column('estado_reemplazo', sa.String(length=50), nullable=True),
    sa.Column('fecha_intento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oferente_id'], ['offix.oferentes.id_oferente'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_validacion'),
    schema='offix'
    )
    op.create_index(op.f('ix_offix_validaciones_matricula_id_validacion'), 'validaciones_matricula', ['id_validacion'], unique=False, schema='offix')
    op.create_index(op.f('ix_offix_validaciones_matricula_oferente_id'), 'validaciones_matricula', ['oferente_id'], unique=False, schema='offix')
    op.create_table('resenas',
    sa.Column('id_resena', sa.Integer(), nullable=False),
    sa.Column('oferente_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=False),
    sa.Column('contacto_cliente_ingresado', sa.String(length=100), nullable=False),
    sa.Column('calificaciones_comentarios', sa.JSON(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['oferente_id'], ['offix.oferentes.id_oferente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['offix.solicitudes_resena.id_solicitud'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_resena'),
    schema='offix'
    )
    op.create_index(op.f('ix_offix_resenas_id_resena'), 'resenas', ['id_resena'], unique=False, schema='offix')
    op.create_index(op.f('ix_offix_resenas_oferente_id'), 'resenas', ['oferente_id'], unique=False, schema='offix')
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('requiere_accion', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('resena_id', sa.Integer(), nullable=True),
    sa.Column('validacion_matricula_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resena_id'], ['offix.resenas.id_resena'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['offix.usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validacion_matricula_id'], ['offix.validaciones_matricula.id_validacion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notificacion'),
    schema='offix'
    )
    op.create_index('idx_notificacion_fecha', 'notificaciones', [sa.text('fecha_creacion DESC')], unique=False, schema='offix')
    op.create_index('idx_notificacion_usuario_estado', 'notificaciones', ['usuario_id', 'estado'], unique=False, schema='offix')
    op.create_index(op.f('ix_offix_notificaciones_id_notificacion'), 'notificaciones', ['id_notificacion'], unique=False, schema='offix')
    op.create_index(op.f('ix_offix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False, schema='offix')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offix_notificaciones_usuario_id'), table_name='notificaciones', schema='offix')
    op.drop_index(op.f('ix_offix_notificaciones_id_notificacion'), table_name='notificaciones', schema='offix')
    op.drop_index('idx_notificacion_usuario_estado', table_name='notificaciones', schema='offix')
    op.drop_index('idx_notificacion_fecha', table_name='notificaciones', schema='offix')
    op.drop_table('notificaciones', schema='offix')
    op.drop_index(op.f('ix_offix_resenas_oferente_id'), table_name='resenas', schema='offix')
    op.drop_index(op.f('ix_offix_resenas_id_resena'), table_name='resenas', schema='offix')
    op.drop_table('resenas', schema='offix')
    op.drop_index(op.f('ix_offix_validaciones_matricula_oferente_id'), table_name='validaciones_matricula', schema='offix')
    op.drop_index(op.f('ix_offix_validaciones_matricula_id_validacion'), table_name='validaciones_matricula', schema='offix')
    op.drop_table('validaciones_matricula', schema='offix')
    op.drop_index(op.f('ix_offix_solicitudes_resena_oferente_id'), table_name='solicitudes_resena', schema='offix')
    op.drop_index(op.f('ix_offix_solicitudes_resena_id_solicitud'), table_name='solicitudes_resena', schema='offix')
    op.drop_index(op.f('ix_offix_solicitudes_resena_codigo_unico'), table_name='solicitudes_resena', schema='offix')
    op.drop_table('solicitudes_resena', schema='offix')
    op.drop_index(op.f('ix_offix_matriculas_oferente_id'), table_name='matriculas', schema='offix')
    op.drop_index(op.f('ix_offix_matriculas_id_matricula'), table_name='matriculas', schema='offix')
    op.drop_table('matriculas', schema='offix')
    op.drop_index(op.f('ix_offix_archivos_adjuntos_oferente_id'), table_name='archivos_adjuntos', schema='offix')
    op.drop_index(op.f('ix_offix_archivos_adjuntos_id_archivo'), table_name='archivos_adjuntos', schema='offix')
    op.drop_table('archivos_adjuntos', schema='offix')
    op.drop_index(op.f('ix_offix_alertas_administrador_oferente_id'), table_name='alertas_administrador', schema='offix')
    op.drop_index(op.f('ix_offix_alertas_administrador_id_alerta'), table_name='alertas_administrador', schema='offix')
    op.drop_table('alertas_administrador', schema='offix')
    op.drop_table('oferentes', schema='offix')
    op.drop_index(op.f('ix_offix_usuarios_id_usuario'), table_name='usuarios', schema='offix')
    op.drop_index(op.f('ix_offix_usuarios_email'), table_name='usuarios', schema='offix')
    op.drop_table('usuarios', schema='offix')
    op.drop_index(op.f('ix_offix_padron_matriculas_tipo_profesional'), table_name='padron_matriculas', schema='offix')
    op.drop_index(op.f('ix_offix_padron_matriculas_numero_matricula'), table_name='padron_matriculas', schema='offix')
    op.drop_index(op.f('ix_offix_padron_matriculas_id_padron'), table_name='padron_matriculas', schema='offix')
    op.drop_table('padron_matriculas', schema='offix')
    op.drop_index(op.f('ix_offix_categorias_id_categoria'), table_name='categorias', schema='offix')
    op.drop_table('categorias', schema='offix')
    # ### end Alembic commands ###
